### ISSUE TITLE
Update instructions to include setting 05-private.py

### ISSUE THREAD

**Issue by smeshoyrer** [freelawproject/freelawmachine#21] opened 2017-01-03 23:53 UTC
Need to flesh out instructions to include setting up personal settings.

**Comment by mlissner** [comment] 2017-01-03 23:59
Right now, it looks like Ansible is setting up a file in `cl/settings/tmp{somerandomjunk}`, but this file should be named `05-private.py`, and the read me should tell people to update it with whatever needed info.

**Comment by smeshoyrer** [comment] 2017-01-04 00:01
within `05-private.py`. the variable `here` is used in the line `'PATH': os.path.join(here,'google_auth.json'),`, but it is never initialized to an empty string, and it is unclear exactly what it should be set to.

**Comment by mlissner** [comment] 2017-01-04 00:29
> within 05-private.py. the variable here is used in the line 'PATH': os.path.join(here,'google_auth.json'),, but it is never initialized to an empty string, and it is unclear exactly what it should be set to.

This part is fixed in CL. It was my mistake.

**Comment by voutilad** [comment] 2017-01-23 20:55
I believe this is an issue in the CourtListener code base and not the Packer and Ansible scripts in the FreeLawMachine project. If not, please reopen and let me know.

**Comment by mlissner** [comment] 2017-01-23 22:06
@voutilad I think the idea here was that we should take the 05-private.py.example file and copy it over to 05-private.py. At the same time, we could put a note in the readme that asks people to review the values in the private.py file.

**Comment by voutilad** [comment] 2017-01-23 22:22
It does that already: https://github.com/freelawproject/freelawmachine/blob/9a0cedef44ac898c8c73c8085c9d270a3fecbcb4/ansible/roles/courtlistener/tasks/django.yml#L7

It's cloning the CourtListener source during provisioning of the box, so if the issue is a question on the contents of `05-private.py.example` it's an issue in the CourtListener project.

If the `05-private.py` file isn't being created in a manner that starting Django fails, then it's an Ansible issue and in this project.

**Comment by mlissner** [comment] 2017-01-23 22:26
OK, yeah, that looks right to me, so closing. @smeshoyrer can you chime in if you have ideas about why this file might not have been created for you?

**Closed by mlissner** 2017-01-23 22:26 UTC
